name: Build and Push Docker Image
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: siniousmaximus
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract tag name and detect branch
        id: tag
        run: |
          TAG=${GITHUB_REF_NAME}
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "Extracted tag: ${TAG}"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            siniousmaximus/service-checker:${{ steps.tag.outputs.TAG }}
            siniousmaximus/service-checker:latest
          cache-from: type=registry,ref=siniousmaximus/service-checker:latest
          cache-to: type=inline

      - name: Update Docker Hub description
        run: |
          REPO="siniousmaximus/service-checker"
          README_CONTENT=$(sed ':a;N;$!ba;s/\n/\\n/g' README.md)
          curl -s -X PATCH "https://hub.docker.com/v2/repositories/$REPO/" \
            -H "Content-Type: application/json" \
            -H "Authorization: JWT ${{ secrets.DOCKERHUB_TOKEN }}" \
            -d "{\"full_description\":\"$README_CONTENT\"}"    
